### ISSUE TITLE
Find a reliable carbon dioxide data set

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#1]
The requirements are:

  1. It must be updated daily
  2. Must be free in price (just assuming here)
  3. Must have appropriate usage license (non-commercial sharing?)
  4. Must cover the world (no idea if this is done, feasible, will need combining)

Just brainstorming here, so please add more constraints if necessary.

**Comment by elliottsencan** [comment]
IMO this is the most challenging part. I havent checked TOS or robots.txt, but we could scrape this no problem https://www.co2.earth/daily-co2

**Comment by titojankowski** [comment]
**Daily data 1975 - 2015** ftp://aftp.cmdl.noaa.gov/data/trace_gases/co2/in-situ/surface/mlo/co2_mlo_surface-insitu_1_ccgg_DailyData.txt

**Current data** Freshest data seems like NOAA's page, last updated yesterday. But would need to be scraped, I don't see a data file for it: https://www.esrl.noaa.gov/gmd/ccgg/trends/monthly.html

_Data repository_
NOAA's data repository filtered for CO2 at MLO (Mauna Loa Observatory). But the data cuts off in 2015...
https://www.esrl.noaa.gov/gmd/dv/data/index.php?parameter_name=Carbon%2BDioxide&site=MLO

Funny how all over the place this data is. Good sign we're onto something big!

**Comment by titojankowski** [comment]
Re "#4: Must cover the world (no idea if this is done, feasible, will need combining"
- My understanding is Mauna Loa is used as the gold standard for "global" CO2 measurement: https://celebrating200years.noaa.gov/datasets/mauna/welcome.html#1958
https://www.nytimes.com/2016/10/04/science/atmospheric-carbon-dioxide-400-ppm.html

For an MVP let's start with Mauna Loa data -- the NOAA and co2.earth sites both use Mauna Loa data.

**Comment by titojankowski** [comment]
Now that we've got a daily dataset that meets all our requirements (https://www.esrl.noaa.gov/gmd/ccgg/trends/monthly.html), we need a scraper to run each day, grab the data, and drop it somewhere so the graph can pull from it. This way we'll have an infinite stream of fresh data every day. @lwm thoughts?

**Comment by lwm** [comment]
I see! I'll get hacking :smile:

**Comment by titojankowski** [comment]
schweeeeeeeeeet!!

**Comment by lwm** [comment]
Nice detective work. So, to summarise, we went with:

* http://aftp.cmdl.noaa.gov/data/trace_gases/co2/in-situ/surface/mlo/co2_mlo_surface-insitu_1_ccgg_DailyData.txt

That's daily C02 measurements from the Mauna Loa Observatory (more about that in https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/1#issuecomment-306661315).

**Comment by titojankowski** [comment]
@lwm just to clarify, that dataset is only up to December 31st, 2015 (ftp://aftp.cmdl.noaa.gov/data/trace_gases/co2/in-situ/surface/mlo/co2_mlo_surface-insitu_1_ccgg_DailyData.txt).

So we'll need a scraper to grab new daily data as it comes out from https://www.esrl.noaa.gov/gmd/ccgg/trends/monthly.html
