### ISSUE TITLE
Bootstrap a modern UX design

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#2]
Examples of nice UX were:

1. https://99bitcoins.com/price-chart-history/
2. https://www.coinbase.com/

Open to any suggestions, recommendations and plans. Just shoot.

**Comment by elliottsencan** [comment]
I think for MVP we iterate on coinbase.com/charts, its beautiful, concise, and is flexible enough to add new features.

**Comment by titojankowski** [comment]
coinbase.com/charts sounds great to me. Coinbase chart, which has "1 month / 1 year / All". It doesn't have the "historical" callouts, though.

Who wants to take a crack at building a first version?

**Comment by lwm** [comment]
I think this is a dupe of https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/5. Closing.
