### ISSUE TITLE
Onboard people to this weird and wonderful adventure

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#4]
We'll need more people if we want to get this going. Where can we find them?

**Comment by elliottsencan** [comment]
I'm suprised hackernews only turned up two people. MVP should include a get involved link prominently, get like minded people involved

**Comment by titojankowski** [comment]
What skills are we missing?
- UX/data: @elliottsencan?
- marketing/PR: @lwm? @titojankowski

**Comment by lwm** [comment]
I'm a back-end guy, so depending on which way we go, I'm not needed ;)

**Comment by lwm** [comment]
> I'm suprised hackernews only turned up two people. MVP should include a get involved link prominently, get like minded people involved

Aye aye!

HN seems to be our entry point for now. Closing.
