### ISSUE TITLE
Scrape the last 5 days worth of CO2 measurements

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#6]
The last 5 days worth of CO2 measurements are recorded at (green box):

* https://www.esrl.noaa.gov/gmd/ccgg/trends/monthly.html

We need to scrape this daily to keep our current data fresh.

This is the easiest bite of work to be done now to start providing data for a front-end.

**Comment by titojankowski** [comment]
Sounds great!

**Comment by titojankowski** [comment]
@lwm the dataset found by @wickedwitch looks like the source for the monthly.html page's data. Worth grabbing the daily data from the source instead?
https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2_mlo_weekly.csv

**Comment by lwm** [comment]
Done in https://github.com/giving-a-fuck-about-climate-change/carbondoomsday-django/issues/1. Closing off.
