### ISSUE TITLE
Source the missing 2015-2017 CO2 measurements

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#8]
Following from https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/7 and https://github.com/giving-a-fuck-about-climate-change/carbon-doomsday/issues/6 we should be in a position to deal with the missing 2015 - 2017 data.

Either we can find it somewhere or the MLO will publish it. We should keep an eye on [the change log](https://www.esrl.noaa.gov/gmd/ccgg/trends/trends_log.html).

**Comment by wickedwitch** [comment]
Found this https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2_mlo_weekly.csv in the second graph of https://www.esrl.noaa.gov/gmd/ccgg/trends/graph.html

it seems to have the daily data from 2015 - 2017
Cheers,
Zee

**Comment by lwm** [comment]
Oh damn @wickedwitch, that is great! Can someone else eyeball that and confirm?

**Comment by titojankowski** [comment]
@lwm i have put not just one but two eyeballs on it. this is solid data, and has data up until today (6/12). It's probably the source of that green graph you're scraping. nice one, @wickedwitch!

**Comment by lwm** [comment]
Well, looks this has been 'sourced'. Closing, well done folks :+1:
