### ISSUE TITLE
Choose a data store

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbon-doomsday#9]
We'll store [time series data](https://en.wikipedia.org/wiki/Time_series_database). However, not too much of it and with no real hard constraints on reading/writing. Is there something against just picking good 'ol postgresql? Open to suggestions but I think postgresql should be just fine.

**Comment by titojankowski** [comment]
works for me. fwiw I've got experience running lots of sql queries while serving time at eBay :)

**Comment by lwm** [comment]
:+1:
